### ISSUE TITLE
v2 and JS API

### ISSUE THREAD

**Issue by bartaz** [alex-page/get-site-urls#29]
Hey, just noticed the v2 released and the move to CLI tool.

I guess it means there is no longer any JS API to use in code directly?

**Comment by alex-page** [comment]
@bartaz not right now. I could expose the API and the CLI. Let me know!

**Comment by bartaz** [comment]
It was definitely convenient for us to get the list of URLs, filter them out and manipulate before passing to another function all within the single JS script. But we can stick to v1 for now, as we don't really need anything more from it.

**Comment by alex-page** [comment]
I will leave this issue open. Happy to add it back but I will gauge some interest. Thanks @bartaz!

**Comment by alex-page** [comment]
@bartaz I just shipped v3 and added back the API. Let me know if you have any thoughts https://github.com/alex-page/get-site-urls#usage

**Comment by bartaz** [comment]
Thanks @alex-page for letting me know, next time renovate asks for get-site-urls update gonna give it a try.
